// src/lib/mockData.ts
import type { Track, PlaylistFilter } from "@/types";

export const MOCK_TRACKS: Track[] = [
  {
    id: "1",
    title: "Motion Sickness",
    artist: "Phoebe Bridgers",
    album: "Stranger in the Alps",
    albumArt: "https://i.scdn.co/image/ab67616d0000b273e5b4d8f15ee7cf98ef2e9b08",
    spotifyUri: "spotify:track:2dSFSzprHxJHF58mHGaGea",
    reason: "dreamy indie energy · underground find",
    previewUrl: null,
  },
  {
    id: "2",
    title: "Retrograde",
    artist: "James Blake",
    album: "Overgrown",
    albumArt: "https://i.scdn.co/image/ab67616d0000b2731f7dd4c2e6b8b2e6b4bbd7d5",
    spotifyUri: "spotify:track:4JZwRoULr8OhToXH1YCmJC",
    reason: "fits the melancholic mood · electronic soul",
    previewUrl: null,
  },
  {
    id: "3",
    title: "Garden Song",
    artist: "Phoebe Bridgers",
    album: "Punisher",
    albumArt: "https://i.scdn.co/image/ab67616d0000b273e5b4d8f15ee7cf98ef2e9b08",
    spotifyUri: "spotify:track:2dSFSzprHxJHF58mHGaGea",
    reason: "warm folk atmosphere · crowd-tested pick",
    previewUrl: null,
  },
  {
    id: "4",
    title: "Skinny Love",
    artist: "Bon Iver",
    album: "For Emma, Forever Ago",
    albumArt: "https://i.scdn.co/image/ab67616d0000b27326f7f19c7f0381e56156c94a",
    spotifyUri: "spotify:track:2kJTLzUJMBSA2cqAz6j7L9",
    reason: "raw folk energy · fits the warm mood",
    previewUrl: null,
  },
  {
    id: "5",
    title: "Electric Feel",
    artist: "MGMT",
    album: "Oracular Spectacular",
    albumArt: "https://i.scdn.co/image/ab67616d0000b2737f3e30b59e8a5e1a6e0ab7f7",
    spotifyUri: "spotify:track:3FtYbEfBqAlGMjSrJZqk8k",
    reason: "synth-pop energy · timeless indie",
    previewUrl: null,
  },
  {
    id: "6",
    title: "Dreams",
    artist: "Fleetwood Mac",
    album: "Rumours",
    albumArt: "https://i.scdn.co/image/ab67616d0000b273e6f407c7f3a0ec98845e4431",
    spotifyUri: "spotify:track:0ofHAoxe9vBkTCp2UQIavz",
    reason: "classic warm vibes · dreamy feel",
    previewUrl: null,
  },
  {
    id: "7",
    title: "CACREP",
    artist: "Men I Trust",
    album: "Untourable Album",
    albumArt: "https://i.scdn.co/image/ab67616d0000b273c1c1a2f2b4b8d2e3f5d6e7f8",
    spotifyUri: "spotify:track:5jP9QJjTXqKQ9JGvBKBGj9",
    reason: "dream pop underground · atmospheric",
    previewUrl: null,
  },
  {
    id: "8",
    title: "No Surprises",
    artist: "Radiohead",
    album: "OK Computer",
    albumArt: "https://i.scdn.co/image/ab67616d0000b2736b1a2e3f4c5d6e7f8a9b0c1d",
    spotifyUri: "spotify:track:10nyNJ6zNy2YVYLrcwLccB",
    reason: "melancholic mood · iconic alternative",
    previewUrl: null,
  },
  {
    id: "9",
    title: "Ribs",
    artist: "Lorde",
    album: "Pure Heroine",
    albumArt: "https://i.scdn.co/image/ab67616d0000b273a4b6b7c8d9e0f1a2b3c4d5e6",
    spotifyUri: "spotify:track:6ie2Bw3xLj2oHFiLsvjc3J",
    reason: "dark electropop · female vocals",
    previewUrl: null,
  },
  {
    id: "10",
    title: "Four Minutes",
    artist: "Caribou",
    album: "Our Love",
    albumArt: "https://i.scdn.co/image/ab67616d0000b273b4c5d6e7f8a9b0c1d2e3f4a5",
    spotifyUri: "spotify:track:3FtYbEfBqAlGMjSrJZqk8k",
    reason: "psychedelic indie · medium energy",
    previewUrl: null,
  },
];

export const MOCK_FILTER: PlaylistFilter = {
  mood: "dreamy",
  energy: "medium-low",
  popularity: "lower",
  vocals: "any",
  genre_bias: ["dream pop", "indie folk"],
  exclude: [],
};
